INSERT INTO projects (title, category, funding_goal, start_date, end_date)VALUES("Reading to Dogs", "Science", 1000, 04/1/2020, 08/1/2020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date)VALUES("Reading to Cats", "Science", 5000, 08/1/2020, 12/1/2020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date)VALUES("Elephants for All", "Recreation", 1245, 3/24/2021, 4/12/2021);
INSERT INTO projects (title, category, funding_goal, start_date, end_date)VALUES("Shells for Slugs", "Conservation", 5967, 2/1/2021, 12/12/2022);
INSERT INTO projects (title, category, funding_goal, start_date, end_date)VALUES("Instruments for Schools", "Education", 12000, 5/10/2020, 10/20/2021);
INSERT INTO projects (title, category, funding_goal, start_date, end_date)VALUES("Jazz for the Deaf", "Education", 987, 6/06/2020, 07/7/2021);
INSERT INTO projects (title, category, funding_goal, start_date, end_date)VALUES("Bumps for the Blind", "Education", 12857, 7/04/2020, 09/10/2020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date)VALUES("Shoes for Dancers", "Recreation", 9876, 9/10/2020, 12/10/2020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date)VALUES("Save the Seals", "Conservation", 10000, 1/1/2020, 12/29/2020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date)VALUES("Free Willy", "Conservation", 10000, 1/2/2020, 5/15/2021);

INSERT INTO users (name, age) VALUES ("Margret", 2);
INSERT INTO users (name, age) VALUES ("Chloe", 3);
INSERT INTO users (name, age) VALUES ("Samantha", 21);
INSERT INTO users (name, age) VALUES ("Healther", 22);
INSERT INTO users (name, age) VALUES ("Wendy", 12);
INSERT INTO users (name, age) VALUES ("Gabriella", 25);
INSERT INTO users (name, age) VALUES ("Cynthia", 34);
INSERT INTO users (name, age) VALUES ("Ginny", 29);
INSERT INTO users (name, age) VALUES ("Henry", 65);
INSERT INTO users (name, age) VALUES ("Stephen", 43);
INSERT INTO users (name, age) VALUES ("Ryan", 56);
INSERT INTO users (name, age) VALUES ("Colin", 32);
INSERT INTO users (name, age) VALUES ("Mary", 12);
INSERT INTO users (name, age) VALUES ("Jesus", 1000);
INSERT INTO users (name, age) VALUES ("Peter", 21);
INSERT INTO users (name, age) VALUES ("Alyce", 24);
INSERT INTO users (name, age) VALUES ("Virginia", 33);
INSERT INTO users (name, age) VALUES ("Joseph", 34);
INSERT INTO users (name, age) VALUES ("Jose", 89);
INSERT INTO users (name, age) VALUES ("Lemuel", 34);

INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15.2,1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 3, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 4, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 5, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 5, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (45, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 6, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (55, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60, 7, 11);
INSERT INTO pledges (amount, user_id, project_id) VALUES (65, 8, 12);
INSERT INTO pledges (amount, user_id, project_id) VALUES (70, 8, 13);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75, 8, 14);
INSERT INTO pledges (amount, user_id, project_id) VALUES (80, 9, 15);
INSERT INTO pledges (amount, user_id, project_id) VALUES (85, 9, 20);
INSERT INTO pledges (amount, user_id, project_id) VALUES (90, 10, 16);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 10, 17);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 4, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 5, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 5, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (45, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 6, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (55, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60, 7, 11);
INSERT INTO pledges (amount, user_id, project_id) VALUES (65, 8, 12);
INSERT INTO pledges (amount, user_id, project_id) VALUES (70, 8, 13);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75, 8, 14);
