INSERT INTO users (name, age) VALUES ("Alex", 10);
INSERT INTO users (name, age) VALUES ("Bob", 15);
INSERT INTO users (name, age) VALUES ("Camille", 20);
INSERT INTO users (name, age) VALUES ("Dominique", 25);
INSERT INTO users (name, age) VALUES ("Elfo", 30);
INSERT INTO users (name, age) VALUES ("Fabrice", 35);
INSERT INTO users (name, age) VALUES ("Georges", 40);
INSERT INTO users (name, age) VALUES ("Helga", 45);
INSERT INTO users (name, age) VALUES ("Ivy", 50);
INSERT INTO users (name, age) VALUES ("Janice", 55);
INSERT INTO users (name, age) VALUES ("Kenny", 60);
INSERT INTO users (name, age) VALUES ("Levi", 65);
INSERT INTO users (name, age) VALUES ("Manuel", 70);
INSERT INTO users (name, age) VALUES ("Nathan", 75);
INSERT INTO users (name, age) VALUES ("Opal", 80);
INSERT INTO users (name, age) VALUES ("Patricia", 85);
INSERT INTO users (name, age) VALUES ("Quentin", 90);
INSERT INTO users (name, age) VALUES ("Rodolph", 95);
INSERT INTO users (name, age) VALUES ("Steve", 100);
INSERT INTO users (name, age) VALUES ("Thomas", 105);


INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project Alpha", "Army", 10, "01/01/1990", "01/01/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project Bravo", "Banjo", 100, "02/02/1991", "02/02/2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project Charly", "Canteloups", 1000, "03/03/1992", "03/03/2022");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project Delta", "Dinosaurs", 10000, "04/04/1993", "04/04/2023");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project Echo", "Enima", 100000, "05/05/1994", "05/05/2024");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project Foxtrot", "Fairy", 1000000, "06/06/1995", "06/06/2025");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project Golf", "Golf", 10000000, "07/07/1996", "07/07/2026");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project Hotel", "Hotel", 100000000, "08/08/1997", "08/08/2027");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project India", "Intelligence", 1000000000, "09/09/1998", "09/09/2028");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project Juliette", "Julienne cut carrots", 10000000000, "10/10/1999", "10/10/2029");


INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
